version: 0.2
    
phases:   
  install:
    runtime-versions:
      dotnet: latest
      
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore Aspcorepipe/Aspcorepipe.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build Aspcorepipe/Aspcorepipe.csproj
      
  post_build:
    commands:
      - echo Publish started on `date`
      - echo $CODEBUILD_SRC_DIR
      - dotnet publish --output ./bin/Release/netcoreapp3.1/publish -c Release --framework netcoreapp3.1 Aspcorepipe/Aspcorepipe.csproj
      - cp Procfile ./bin/Release/netcoreapp3.1/publish
      - cp aws-windows-deployment-manifest.json ./bin/Release/netcoreapp3.1/publish
      - echo publish done on `date`
      - echo pwd `pwd`
      
artifacts:
  files:
    - '\**\*'
  base-directory: ./bin/Release/netcoreapp3.1/publish
  discard-paths: no